name: PRs to Dev

on:
  pull_request:
    branches: [development]

jobs:
  'build-test-package-artifacts':
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          cache: yarn

      - name: Install packages with Yarn
        run: yarn install --frozen-lockfile

      - name: Build with webpack
        run: yarn build

      - name: Run unittests
        run: yarn checks

      - name: Copy files for E2E tests (!macOS)
        if: matrix.os != 'macos-latest'
        shell: bash
        run: cp -R ./build/* ./src/electron

      - name: Run E2E tests with TestCafe action (!macOS)
        if: matrix.os != 'macos-latest'
        uses: DevExpress/testcafe-action@latest
        env:
          NODE_ENV: test
        with:
          args: 'electron:./src/electron ./tests-e2e'

      - name: Remove files for E2E tests (!macOS)
        if: matrix.os != 'macos-latest'
        shell: bash
        run: rm -rf ./src/electron/dist ./src/electron/main.js

      - name: Package with electron-builder
        run: yarn package:x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Upload apps to artifact store'
        uses: kittaakos/upload-artifact-as-is@v0
        with:
          path: release/TokelPlatform*
